image: docker:git

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab-registry.nautilus.optiputer.net

stages:
  - build-and-push

build-and-push-job:
  stage: build-and-push
  tags:
    - build-as-docker
  script:
    - docker build -t gitlab-registry.nautilus.optiputer.net/jiacheng/nautilus:${CI_COMMIT_SHA:0:8} .
    - docker tag gitlab-registry.nautilus.optiputer.net/jiacheng/nautilus:${CI_COMMIT_SHA:0:8} gitlab-registry.nautilus.optiputer.net/jiacheng/nautilus:latest
    - docker push gitlab-registry.nautilus.optiputer.net/jiacheng/nautilus
