apiVersion: batch/v1
kind: Job
metadata:
  name: jiacheng3  # specify your job name here
spec:
  template:
    spec:
      containers:
      - name: gpu-container
        image: gitlab-registry.nautilus.optiputer.net/jiacheng/docker-images:sgbv3-simd
        command: ["/bin/sh","-c"]
        args:
        - cd /data/jiacheng/rfs;
          bash ./run.sh;
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /dev/shm
          name: dshm
        resources:
          limits:
            memory: 32Gi
            nvidia.com/gpu: "1"
            cpu: "2"
          requests:
            memory: 8Gi
            nvidia.com/gpu: "1"
            cpu: "0.5"
      restartPolicy: Never
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: storage
        - name: dshm
          emptyDir:
            medium: Memory
  backoffLimit: 1

        
