apiVersion: v1
kind: Pod
metadata:
  name: jiacheng0
spec:
  containers:
  - name: gpu-container
    image: gitlab-registry.nautilus.optiputer.net/jiacheng/docker-images:sgbv3
    args: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: /data
      name: data
    - mountPath: /dev/shm
      name: dshm
    resources:
      limits:
        memory: 3Gi
        nvidia.com/gpu: "1"
        cpu: "2"
      requests:
        memory: 3Gi
        nvidia.com/gpu: "1"
        cpu: "2"
  restartPolicy: Never
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: storage
    - name: dshm
      emptyDir:
        medium: Memory
        
