apiVersion: batch/v1
kind: Job
metadata:
  name: jiacheng3 # specify your job name here
spec:
  template:
    spec:
      containers:
      - name: gpu-container
        image: gitlab-registry.nautilus.optiputer.net/jiacheng/docker-images:sgbv3
        command: ["/bin/sh","-c"]
        args:
        - bash /data/jiacheng/Cifar100/prepare_tinyImage.sh;
          cd /data/jiacheng/Cifar100;
          bash run.sh;
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /dev/shm
          name: dshm
        resources:
          limits:
            memory: 8G
            nvidia.com/gpu: "2"
            cpu: "2"
          requests:
            memory: 8G
            nvidia.com/gpu: "2"
            cpu: "2"
      restartPolicy: Never
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: storage
        - name: dshm
          emptyDir:
            medium: Memory
  backoffLimit: 1

        
