apiVersion: batch/v1
kind: Job
metadata:
  name: jiacheng  # specify your job name here
spec:
  template:
    spec:
      containers:
      - name: gpu-container
        image: gitlab-registry.nautilus.optiputer.net/jiacheng/docker-images:gym
        command: ["/bin/sh","-c"]
        args:
        - conda install -y yaml;
          git clone https://github.com/Ian-Mint/pong-underwater-rl.git;
          cd pong-underwater-rl/scripts;
          python run-job.py -u ian -n 111 112 113 -f configs/111.yml configs/112.yml configs/113.yml -m 15 -c 3;
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /dev/shm
          name: dshm
        resources:
          limits:
            memory: 8Gi
            nvidia.com/gpu: "1"
            cpu: "8"
          requests:
            memory: 8Gi
            nvidia.com/gpu: "1"
            cpu: "8"
      restartPolicy: Never
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: storage
        - name: dshm
          emptyDir:
            medium: Memory
  backoffLimit: 1

        
