apiVersion: v1
kind: Pod
metadata:
  name: jiacheng
spec:
  containers:
  - name: gpu-container
    image: gitlab-registry.nautilus.optiputer.net/jerryyli/docker-test:559f099b
    args: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: /data
      name: data
    - mountPath: /dev/shm
      name: dshm
    resources:
      limits:
        memory: 8Gi
        nvidia.com/gpu: 1
      requests:
        memory: 8Gi
        nvidia.com/gpu: 1
  restartPolicy: Never
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: storage
    - name: dshm
      emptyDir:
        medium: Memory
        
